import Link from "next/link";
import { apiGet } from "@/lib/api";
import { AuditStream } from "./components/AuditStream";
import { MetricCard } from "./components/MetricCard";
import { RecoveryFunnel } from "./components/RecoveryFunnel";
type Overview = { total_cases: number; razorpay_test_confirmed_recovery: number; simulated_confirmed_recovery: number; pending_promises: number; blocked_actions: number; unresolved_cases: number; human_escalations: number };
type Stage = { stage: string; count: number }; type Evaluation = { split: string; total: number; recovered: number; recovery_rate: number; amount_recovered: number };
export default async function Dashboard() {
  const [overview, funnel, evaluation] = await Promise.all([apiGet<Overview>("/api/dashboard/overview"), apiGet<Stage[]>("/api/dashboard/funnel"), apiGet<Evaluation[]>("/api/dashboard/evaluation")]); const inr = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" });
  return <main className="min-h-screen bg-slate-50 p-8 text-slate-950"><header className="mb-8"><p className="text-sm font-semibold uppercase text-emerald-700">AI Revenue Recovery</p><h1 className="text-4xl font-bold">Vasooli Control Room</h1><p className="mt-2 text-slate-600">Confirmed, simulated and pending outcomes are reported separately.</p><nav className="mt-4 flex flex-wrap gap-4 text-emerald-700">{[["/cases","Recovery queue"],["/incidents","Incidents"],["/mandates","Mandates"],["/invoices","Invoices"],["/promises","Promises"]].map(([href,label]) => <Link href={href} key={href}>{label}</Link>)}</nav></header><section className="grid gap-4 md:grid-cols-3 xl:grid-cols-4"><MetricCard label="Razorpay Test Mode confirmed" value={inr.format(overview.razorpay_test_confirmed_recovery)} accent /><MetricCard label="Simulated confirmed" value={inr.format(overview.simulated_confirmed_recovery)} /><MetricCard label="Pending promises" value={overview.pending_promises} /><MetricCard label="Blocked actions" value={overview.blocked_actions} /><MetricCard label="Unresolved cases" value={overview.unresolved_cases} /><MetricCard label="Human escalations" value={overview.human_escalations} /><MetricCard label="Total cases" value={overview.total_cases} /></section><section className="mt-8"><h2 className="mb-3 text-2xl font-semibold">Recovery funnel</h2><RecoveryFunnel data={funnel} /></section><section className="mt-8"><h2 className="mb-3 text-2xl font-semibold">Development vs held-out</h2><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-left"><thead className="bg-slate-100"><tr>{["Split", "Cases", "Recovered", "Rate", "Amount"].map(x => <th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{evaluation.map(row => <tr key={row.split} className="border-t"><td className="p-3">{row.split}</td><td className="p-3">{row.total}</td><td className="p-3">{row.recovered}</td><td className="p-3">{(row.recovery_rate * 100).toFixed(1)}%</td><td className="p-3">{inr.format(row.amount_recovered)}</td></tr>)}</tbody></table></div></section><div className="mt-8"><AuditStream /></div></main>;
}
