"""add day3 integration tables

Revision ID: 8776d4adf8e0
Revises: 97c8d45b1f56
Create Date: 2026-09-05 20:32:12.830488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8776d4adf8e0'
down_revision: Union[str, Sequence[str], None] = '97c8d45b1f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_message_id')
    )
    op.create_index(op.f('ix_communication_events_case_id'), 'communication_events', ['case_id'], unique=False)
    op.create_table('provider_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('provider_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_event')
    )
    op.create_index('ix_provider_event_case_type', 'provider_events', ['case_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_provider_events_case_id'), 'provider_events', ['case_id'], unique=False)
    op.create_table('provider_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('provider_reference_id', sa.String(length=255), nullable=False),
    sa.Column('provenance', sa.Enum('RAZORPAY_TEST', 'SYNTHETIC', 'DERIVED', 'LLM_INFERRED', 'SIMULATED_OUTCOME', name='provenance'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'reference_type', 'provider_reference_id', name='uq_provider_reference')
    )
    op.create_index(op.f('ix_provider_references_case_id'), 'provider_references', ['case_id'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('twilio_call_sid', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('final_intent', sa.String(length=50), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_call_sid')
    )
    op.create_index(op.f('ix_voice_sessions_case_id'), 'voice_sessions', ['case_id'], unique=False)
    op.add_column('recovery_cases', sa.Column('recommended_action', sa.String(length=100), nullable=True))
    op.add_column('recovery_cases', sa.Column('workflow_type', sa.String(length=100), nullable=True))
    op.add_column('recovery_cases', sa.Column('funnel_stage', sa.String(length=50), server_default='DETECTED', nullable=False))
    op.add_column('recovery_cases', sa.Column('provider_status', sa.String(length=50), nullable=True))
    op.add_column('recovery_cases', sa.Column('outcome_provenance', sa.String(length=50), nullable=True))
    op.add_column('recovery_cases', sa.Column('failure_code', sa.String(length=100), nullable=True))
    op.add_column('recovery_cases', sa.Column('failure_description', sa.Text(), nullable=True))
    op.add_column('recovery_cases', sa.Column('latest_payment_url', sa.Text(), nullable=True))
    op.add_column('recovery_cases', sa.Column('invoice_disputed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'invoice_disputed')
    op.drop_column('recovery_cases', 'latest_payment_url')
    op.drop_column('recovery_cases', 'failure_description')
    op.drop_column('recovery_cases', 'failure_code')
    op.drop_column('recovery_cases', 'outcome_provenance')
    op.drop_column('recovery_cases', 'provider_status')
    op.drop_column('recovery_cases', 'funnel_stage')
    op.drop_column('recovery_cases', 'workflow_type')
    op.drop_column('recovery_cases', 'recommended_action')
    op.drop_index(op.f('ix_voice_sessions_case_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index(op.f('ix_provider_references_case_id'), table_name='provider_references')
    op.drop_table('provider_references')
    op.drop_index(op.f('ix_provider_events_case_id'), table_name='provider_events')
    op.drop_index('ix_provider_event_case_type', table_name='provider_events')
    op.drop_table('provider_events')
    op.drop_index(op.f('ix_communication_events_case_id'), table_name='communication_events')
    op.drop_table('communication_events')
    # ### end Alembic commands ###
